### ISSUE TITLE
how to handle Page crashed  error ,when execute the run method。

### ISSUE THREAD

**Issue by susakin** [facebook/memlab#114]
![微信截图_20240221173312](https://github.com/facebook/memlab/assets/12101570/01709552-ad1c-49ed-a6ab-5b660dacddb7)

 try {
    const { leaks, runResult } = await run({ scenario });
    } catch(e) {
     console.log(e)
    }
    
   try catch can not  handle this error,  i need to get this error  to return to service

**Comment by JacksonGL** [comment]
This is a puppeteer error that does not seem to be catchable. This is likely because the browser OOMed (out-of-memory crashed). I would recommend testing on a scenario where the web app uses less memory; or perhaps also the solution here: https://github.com/puppeteer/puppeteer/issues/1321#issuecomment-378361236
