### ISSUE TITLE
'beforeInitialPageLoad' does not exist in type 'IScenario'

### ISSUE THREAD

**Issue by asdjgfr** [facebook/memlab#49]
Until the latest version *(v1.1.33)* `beforeInitialPageLoad` not working.
But i saw it's already in [core](https://github.com/facebook/memlab/commit/1de623fc2c9dfedf7f0df5ac7f0024298f463b7c) and [docs](https://facebook.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-beforeinitialpageload-interactionscallback).
Did I use it incorrectly?

![image](https://user-images.githubusercontent.com/23442840/199441638-30ae2c01-4944-4135-b176-4b5a2da57cd1.png)

**Comment by JacksonGL** [comment]
@asdjgfr `beforeInitialPageLoad` should be available since v1.1.30. Please double check the version you are using (there is a `memlab version` command).

**Comment by JacksonGL** [comment]
@asdjgfr The type mismatch is probably because puppeteer types are not compatible across different versions. The `Page` type from puppeteer under your projects' `node_modules/puppeteer` directory is different from the `Page` type defined under `node_modules/@memlab/core/node_modules/puppeteer` directory. 

One way to fix is align the puppeteer type by `npm install puppeteer@<version>` (`version` is the puppeteer version under `node_modules/@memlab/core/node_modules/puppeteer`).

**Comment by asdjgfr** [comment]
@JacksonGL Thx, run `memlab version` command gets the flowing information:
```
memlab@1.1.33
 @memlab/heap-analysis@1.0.10
 @memlab/e2e@1.0.13
 @memlab/core@1.1.12
 @memlab/cli@1.0.15
 @memlab/api@1.0.12
```
`@memlab/api` version incorrectly.
Removed `node_modules` and `package-lock.json` then reinstall dependencies fixed this issue.
