### ISSUE TITLE
More recent Chrome version / Apple Silicon support

### ISSUE THREAD

**Issue by eelco** [facebook/memlab#57]
Currently memlab is using a relatively old version of Puppeteer, which uses an old version of Chrome (101). It’s also running the Intel version on Apple Silicon macs, which likely is not helping performance when taking huge heap snapshots. (I’m writing this issue while waiting on a 1GB heap snapshot.)

Can this be upgraded to a more recent version?

**Comment by JacksonGL** [comment]
@eelco At the moment, memlab is using an older version of puppeteer because the code is shared and used for internal testing at Meta and there are certain factors that leads to the use of the older version for now. We may update the code in the future to allow MemLab OSS to use the latest version of puppeteer.

I tried using a local build with Puppeteer@19.4.1 + Chromium 109 to see if it would improve performance when taking heap snapshots, but I did not notice a significant speedup on my machine. I'm curious if you have experienced a different result on your machine.

**Comment by eelco** [comment]
Thanks for the clarification!

My issue is for two things:
- A recent version of Chrome
- An ARM version of Chrome on Macs with an Apple Silicon processor

I expect performance gains to come from the latter, but both require a more recent version of Puppeteer, which is why I created a single issue.

**Comment by timocov** [comment]
Looks like puppeteer has been upgraded in https://github.com/facebook/memlab/commit/872b30238f1728cbcdebfb9800d54972f8669d62
