### ISSUE TITLE
oversized-object.js conclusion is incorrect

### ISSUE THREAD

**Issue by fullstackren** [facebook/memlab#66]
I run the command（memlab run --scenario ~/memlab/scenarios/oversized-object.js）and find the data and graphics are correct, but the conclusion is incorrect(No leaks found, MemLab found 0 leak(s)).

![04](https://user-images.githubusercontent.com/109937620/224278733-15df3dc3-c007-402b-801c-0aea0a68ba2f.png)

**Comment by JacksonGL** [comment]
By default, large objects are not flagged as memory leaks since they could be caches created by the web app. However, if you want to identify large objects using MemLab, use the `--trace-object-size-above` option. 

For example, you can set the flag to check objects larger than 1KB:
```bash
memlab run --scenario ~/memlab/scenarios/oversized-object.js --trace-object-size-above 1000
```

MemLab also supports self-defined leak detector with the [`leakFilter` callback](https://facebook.github.io/memlab/docs/api/interfaces/core_src.ILeakFilter/#-leakfilter-leakfiltercallback).

You can start with marking all objects allocated as leak and then refine the leak detector based on your app:
```javascript
leakFilter(node, snapshot, leakedNodeIds) {
  return true;
}
```
Note: the callback could also be defined in the scenario file.

Please also check out this doc:
https://facebook.github.io/memlab/docs/guides/guides-find-leaks
